inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - '**/*~'

Layout/LineLength:
  Exclude:
    - '**/*.gen.rb'

Style/AsciiComments:
  Enabled: false
